### ISSUE TITLE
importURL is wrong in FullyKioskBrowserController.groovy

### ISSUE THREAD

**Issue by sgrayban** [GvnCampbell/Hubitat#1]
You have:

`https://github.com/GvnCampbell/Hubitat/blob/master/Drivers/FullyKioskBrowserController.groovy`

It should point to the raw url

`https://raw.githubusercontent.com/GvnCampbell/Hubitat/master/Drivers/FullyKioskBrowserController.groovy`

**Comment by GvnCampbell** [comment]
Thanks for the correction.  I've updated the code.
