### ISSUE TITLE
TTS doesn't work through Rule 5.0

### ISSUE THREAD

**Issue by flyjmz** [GvnCampbell/Hubitat#3]
TTS only works on the device page, automations using this device driver don't work (e.g. Rule 5.0 in Hubitat) after update 2.2.9.  Hubitat user @arnb found the solution:

Change line 302 from 
def speak(text) {

to
def speak(text, volume=50) {

(or set volume to whatever you want, I used 100)

**Comment by GvnCampbell** [comment]
Thanks for reporting this.  Fixed in 1.41.
